name: Auto commit

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Modify file
        run: |
          date '+%d-%m-%Y %I:%M:%S %p' > LAST_UPDATED

      - name: Commit and Push Changes
        run: |
          git config --local user.email "parikshit.tunlr@slmail.me"
          git config --local user.name "Parixshit"
          git add LAST_UPDATED
          git commit -s -m "feat: auto commit"
          git push -u origin master
