name: Auto commit

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Modify, Commit and Push Changes
        run: |
          git config --local user.email "parikshit.tunlr@slmail.me"
          git config --local user.name "Parixshit"
          chmod +x auto_commit.sh && bash auto_commit.sh
          git push -u origin master
