name: Auto commit

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Modify file
        run: |
          d=`date '+%d-%m-%Y %I:%M:%S %p'`
          echo $d > LAST_UPDATED

      - name: Commit changes
        run: |
          git config --local user.email "parikshit.tunlr@slmail.me"
          git config --local user.name "Parixshit"
          git add LAST_UPDATED
          git commit -s -m "feat: auto commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
