name: Auto commit

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 6 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Modify file
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED

      - name: Commit changes
        run: |
          git config --local user.email "parikshit.tunlr@slmail.me"
          git config --local user.name "Parixshit"
          git add -A
          emojis=("💻" "📱" "🚀" "🛸" "🔭" "📡" "🔬" "🧬" "🧪" "🌡️" "⚡" "🔌" "🕹️" "🎮" "👾" "🕰️" "💾" "💿" "🖨️" "📷" "🎥" "🎞️" "🎬" "🎧" "🎤" "🎵" "🎶" "🎼" "🔊" "🎙️" "🎛️" "🎚️" "🎧" "🎸" "🎺" "🎷" "🥁" "🎻" "📻" "🔍" "🔬")
          rand_emoji=${emojis[$RANDOM % ${#emojis[@]}]}
          git commit -m "feat: ${rand_emoji} auto commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
