name: Auto commit

on:
  push:
    branches:
      - workflow
  schedule:
    - cron: "0 0 * * 0,1,3,4,6"
  workflow_dispatch:
    inputs:
      num_commits:
        description: The number of commits to generate
        default: "5"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --local user.email "87859520+Parixshit@users.noreply.github.com"
          git config --local user.name "Parixshit"

      - name: Generate commits
        run: |
          num_commits=${{ inputs.num_commits }}
          if [[ -z "$num_commits" ]]; then
            num_commits=$(( RANDOM % 30 + 1 ))
          fi
          for i in $(seq $num_commits); do
            commit_date=$(date -d "-$i days -1 year" +"%Y-%m-%d %H:%M:%S")
            readme_date=$(date -d "$commit_date" +"%a, %d %b %Y %T")
            commit_message="Auto commit: iteration $i of $num_commits 🚀 on $commit_date
          - This is an automated commit generated by a GitHub Actions workflow."
            echo -e "**_Commit date: ${readme_date}_**" > README.md
            git add README.md
            git commit -s --date="$commit_date" -m "$commit_message"
            sleep 1
          done

      - name: Push changes
        run: git push origin main
